#!/usr/bin/env Rscript
args = commandArgs(trailingOnly=TRUE)
HOME=args[1]
munge=args[2]

print("Load R packages and functions")
source(paste0(HOME, "/analysis/input.R"))
source(paste0(HOME, "/analysis/functions.R"))
library(GenomicSEM)
library(ieugwasr)
library(TwoSampleMR)


con <- file(paste0(HOME, "/output/log/ldscReg_PS.log"))
sink(con, append=TRUE, type="output")

drop_auth(rdstoken = paste0(HOME, "/token.rds"))  # authentication for dropbox
drop_download(
  local_path = paste0(HOME,"/data/gwaDat.xlsx"),
  path = paste0(LOCAL,"/data/gwaDat.xlsx"), overwrite=TRUE)

print("Read in names for external sumstats")
library("readxl")
gwaList <- readxl::read_excel(paste0(HOME, "/data/gwaDat.xlsx"))
gwasSumStast=subset(gwaList, includeLDSC=="yes")
gwasSumStast$DirPath=paste0(GWA,gwasSumStast$fileName)

print("Read in names for sumstats also used in MR")
drop_download(
  local_path = paste0(HOME,"/data/variableList.xlsx"),
  path = paste0(LOCAL,"/data/variableList.xlsx"), overwrite=TRUE)

variableList <- readxl::read_excel(paste0(HOME, "/data/variableList.xlsx"))
ldscSel=subset(variableList, includeLDSC=="yes")$recodedName
idSel=subset(variableList, includeLDSC=="yes")$ieugwasrID

print("Get sample prevalence")
samplePrevList=lapply(idSel, function(x) extractPrev(x) )
datPrev=as.data.frame(do.call("rbind", samplePrevList))

print("Get population prevalence")
phenoFile=fread(paste0(HOME, "/data/UKBB/phenoFile"))
for ( i in 1:NROW(ldscSel) ) {
  if(is.na( as.numeric(datPrev$sample.prev[i]) )==T ){
      print("non-binary")
      datPrev$population.prev[i]=NA
  } else {
       print("binary")
       datPrev$population.prev[i]=prop.table(table(phenoFile[[ ldscSel[i] ]]))[2] 
  }
  datPrev$label[i]=ldscSel[i]
}

if(munge=="yes"){

print("Prepare clean datasets for munging")
for ( i in 1:length(gwasSumStast$DirPath) ) {
  setwd(paste0(HOME,"/output/ldsc"))
  print(gwasSumStast$label_clean[i])

  if(file.exists(paste0(HOME, "/output/ldsc/", gwasSumStast$label[i], "_clean"))) next

  gwa_in=fread(gwasSumStast$DirPath[i], fill=TRUE )
  colnames(gwa_in)
  gwa_select=subset(gwa_in , select=c(gwasSumStast$SNP[i],
                                      gwasSumStast$A1[i],
                                      gwasSumStast$A2[i],
                                      gwasSumStast$effect[i],
                                      gwasSumStast$se[i],
                                      gwasSumStast$P[i]))
  gwa_select$N=gwasSumStast$N[i]
  colnames(gwa_select)=c("SNP", "A1", "A2", "BETA", "SE", "P", "N")
  gwa_select$BETA=as.numeric(gwa_select$BETA)
  gwa_select$SE=as.numeric(gwa_select$SE)
  gwa_select$P=as.numeric(gwa_select$P)

  gwa_unique=gwa_select[!duplicated(gwa_select$SNP)]
  print(paste0("Remove ", NROW(gwa_select)-NROW(gwa_unique), " duplicate SNPs"))
  # Save output
  print("Save output")
  fwrite(gwa_unique, 
       paste0(HOME, "/output/ldsc/", gwasSumStast$label[i], "_clean"),
       col.names = TRUE,
       row.names = FALSE, 
       quote = F, 
       sep = "\t")
 
}


mungeFiles=c(paste0(gwasSumStast[["label"]], "_clean"),
             paste0("mrcieu_", ldscSel))

dir(paste0(HOME, "/output/ldsc/"))
print("Munge files")
lapply(mungeFiles, function(x) mungeData(x))
}

print("Get heritability estimates and intercept")
dfldsc1=subset(gwasSumStast, select=c(label, sample.prev, population.prev))
dfldsc1$file=paste0(dfldsc1$label, "_clean")
dfldsc2=data.frame(label="ldak_PS_weighted", sample.prev=NA , population.prev=NA) # use munged data generated by LDAK
dfldsc2$file=dfldsc2$label
dfldsc3=subset(datPrev, select=c(label, sample.prev, population.prev))
dfldsc3$file=paste0("mrcieu_",dfldsc3$label)
ldscFiles=rbind(dfldsc1, dfldsc2, dfldsc3)



# function for ldscore
h2outList=list()
for ( i in 1:NROW(ldscFiles) ) {

  print(paste0("Start ", ldscFiles$label[i]))

  print("Estimate heritability")

  ldsch2=NULL
  ldsch2=ldsc(traits=rep(paste0(HOME,"/output/ldsc/", ldscFiles$file[i], ".sumstats.gz"),2),
              sample.prev= rep(as.numeric(ldscFiles$sample.prev[i] ),2),
              population.prev=rep(as.numeric(ldscFiles$population.prev[i] ),2) ,
                           ld=paste0(HOME,"/data/eur_w_ld_chr/"),
                        wld=paste0(HOME,"/data/eur_w_ld_chr/"),
              trait.names = rep(ldscFiles$label[i],2),
              stand=T)

  print("Get standard error")
  h2_t1=ldsch2[["S"]][1]
  SE=NULL
  SE<-matrix(0, nrow(ldsch2[["S"]]), nrow(ldsch2[["S"]]))
  SE[lower.tri(SE,diag=TRUE)] <-sqrt(diag(ldsch2[["V"]]))
  h2_t1_se=SE[1]

  h2outList[[i]]=data.frame(trait=ldscFiles$label[i],
                            h2=h2_t1,
                            h2_se=h2_t1_se,
                            intercept=ldsch2[["I"]][1],
                            file = ldscFiles$file[i])

}
print("Save results on cluster")
h2outDF=as.data.frame (do.call("rbind", h2outList))

saveRDS(h2outDF, paste0(HOME, "/results/rds/h2outDF.rds"))
uploadDropbox(file="h2outDF.rds", folder="rds")



# =========== LD score regression
print("Start ld score regression analysis")
listLDSC=list()
ldscFilesSel=subset(ldscFiles, label!="ldak_PS_weighted")


setwd(paste0(HOME,"/output/ldsc"))

  for ( i in 1:NROW(ldscFilesSel) ) {
    print(paste0("Start ", ldscFilesSel$label[i]))

    LDSCoutputLoop=ldsc(traits=c(paste0(HOME,"/output/ldsc/gwaPS.sumstats.gz"),
                                 paste0(HOME,"/output/ldsc/", ldscFilesSel$file[i], ".sumstats.gz")),
                        sample.prev= c(NA, as.numeric(ldscFilesSel$sample.prev[i] )),
                        population.prev=c(NA, as.numeric(ldscFilesSel$population.prev[i] )),
                        ld=paste0(HOME,"/data/eur_w_ld_chr/"),
                        wld=paste0(HOME,"/data/eur_w_ld_chr/"),
                        trait.names = c("ldak_PS_weighted", ldscFilesSel$label[i]),
                        stand=T)

    print("Get standard errors of ldscore regression")
    k<-nrow(LDSCoutputLoop[["S_Stand"]])
    SE<-matrix(0, k, k)
    SE[lower.tri(SE,diag=TRUE)] <-sqrt(diag(LDSCoutputLoop[["V_Stand"]]  ))
    rg_se=SE[2,1]
    print(paste0("Finished ", ldscFilesSel$label[i]))

    listLDSC[[i]]=data.frame(trait=ldscFilesSel$label[i],
                             file = ldscFilesSel$file[i],
                             rg=LDSCoutputLoop[["S_Stand"]][1,2],
                             rg_se=rg_se)

  }

ldscExternalOutDF=as.data.frame(do.call("rbind", listLDSC))

print("Save results on cluster")
saveRDS(ldscExternalOutDF, paste0(HOME, "/results/rds/ldscExternalOutDF.rds"))
uploadDropbox(file="ldscExternalOutDF.rds", folder="rds")

uploadLog(file=paste0("ldscReg_PS.log"))
uploadLog(file=paste0("ldscReg.log"))